[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "SO-ARM Mimic Extension"
author = "RST Spark"
maintainer = "RST Spark"
description="SO-ARM 101 Robot Extension for Isaac Lab Mimic"
repository = ""
keywords = ["extension", "so_arm", "isaaclab", "mimic"]

[dependencies]
"isaaclab" = {}
"isaaclab_mimic" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "so_arm_mimic"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
